run:
	g++ -o main main.cpp \
	./source/ComputingMachine.cpp \
	./source/laptop.cpp \
	./source/mono.cpp \
	./source/portableMachine.cpp \
	./source/stationMachine.cpp \
	./source/tablet.cpp \
	./myf.cpp

