run:
	g++ -o main main.cpp \
	./source/ComputingMachine.cpp \
	./source/Laptop.cpp \
	./source/mono.cpp \
	./source/portableMachine.cpp \
	./source/stationMachine.cpp \
	./source/Tablet.cpp \
	./myf.cpp

